# https://github.com/jekyll/minima
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
title: s3d.rs
minima:
  skin: classic
  social_links:
    github: s3d-rs
header_pages:
  - docs/user-guide.md
  - docs/developer-guide.md
  - docs/architecture.md
