name: RELEASE

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Fuse
        run: sudo apt-get install -y fuse libfuse-dev pkg-config
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Rust
        uses: Swatinem/rust-cache@v1
      - name: Make Build Release
        run: make build RELEASE=1
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/debug/s3
            target/debug/s3d
